# Configuration specific to the application service. All fields (unless otherwise marked) are required.
homeserver:
  # The domain for the client-server API calls.
  url: "http://homeserver:8008"

  # The domain part for user IDs on this home server. Usually, but not always, this is the same as the
  # home server's URL.
  domain: "matrix.ms.local"

# Configuration specific to the bridge. All fields (unless otherwise marked) are required.
webhookBot:
  # The localpart to use for the bot. May require re-registering the application service.
  localpart: "webhooks"

  # Appearance options for the Matrix bot
  appearance:
    displayName: "Webhook Bridge"
    avatarUrl: "http://i.imgur.com/IDOBtEJ.png" # webhook icon

# Provisioning API options
provisioning:
  # Your secret for the API. Required for all provisioning API requests.
  secret: 8sRqS76LUNRM6W6Z8p5syJMqdBUajcxM2wTC9hpZXh3N8ZKh8Es3oGoGHbPM853j

# Configuration related to the web portion of the bridge. Handles the inbound webhooks
web:
  hookUrlBase: 'https://webhooks.ms.local'

logging:
  file: logs/webhook.log
  console: true
  consoleLevel: debug
  fileLevel: verbose
  writeFiles: true
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5
